```{r data generation, echo = FALSE, results = "hide"}
library(exams)
## https://cerebralmastication.com/2020/07/27/using-python-sympy-in-a-python-code-chunk-in-rmarkdown/
## In console, I ran: reticulate::conda_install("r-reticulate","sympy")
library(reticulate)
deg = sample(2:5,1)
if(deg>5){
  ncomp = sample(c(0,2,4),1)
} else if(deg>2) {
  ncomp = sample(c(0,2),1)
} else {
  ncomp = 0
}

nreal = deg-ncomp
nrep = sample(0:(nreal%/%2),1)
nunq = nreal-nrep

### complex roots represented as a+bi
a = sample(-5:5,ncomp/2)
b = sample(1:5,ncomp/2)
unq = sample(-5:5,nunq)
rep = sample(rep(unq,2),nrep,T)

mult = sample(1:3,1)*sample(c(-1,1),1)

s = ""
if(ncomp>0){
  s = paste0("(x-(",a[1],"-",b[1],"*I))*(x-(",a[1],"+",b[1],"*I))")
}
if(ncomp==4){
  s = paste0(s,"*(x-(",a[2],"-",b[2],"*I))*(x-(",a[2],"+",b[2],"*I))")
}

s2 = paste0("(x-(",unq,"))",collapse="*")
s3 = paste0("(x-(",rep,"))",collapse="*")

if(ncomp>0 & nunq>0 & nrep>0){
  sss = paste0(s,"*",s2,"*",s3)
}
if(ncomp>0 & nunq>0 & nrep==0){
  sss = paste0(s,"*",s2)
}
if(ncomp>0 & nunq==0){
  sss = s
}
if(ncomp==0 & nunq>0 & nrep>0){
  sss = paste0(s2,"*",s3)
}
if(ncomp==0 & nunq>0 & nrep==0){
  sss = paste0(s2)
}
sss = paste(mult,"*",sss)
```


Question
========

```{r}
print(unq)
print(rep)
print(a)
print(b)
```

Consider the polynomial function below, shown in factored and expanded forms.


```{python,echo=F}
from sympy import *
x = symbols("x")
a = parse_expr(r.sss).factor()
b = a.expand()
x_maxima = real_roots(diff(b),x)
y_maxima = []
for xm in x_maxima:
  y_maxima.append(N(b.subs(x,xm),5))
if len(y_maxima)>0 and max(map(abs,y_maxima))>0.0001:
  yma = max(map(abs,y_maxima))*1.1
else:
  left = abs(N(b.subs(x,-6)))
  right = abs(N(b.subs(x,6)))
  yma = min(left,right)
yma = int(yma)
aa = latex(a)
bb = latex(b)
rts = real_roots(b,x)
```

$$f(x) = `r py$aa`$$

$$f(x) = `r py$bb` $$


Solution
========

```{r,echo=F}
eval(parse(text=paste0("f=function(x){",py$b,"}")))
xx = seq(-7,7,0.1)
ym = py$yma
plot(xx,f(xx),type="l",ylim=c(-ym,ym),lwd=4,axes=F,xlab="x",ylab="f(x)",xlim=c(-6.5,6.5))
abline(h=0)
abline(v=0)
axis(1,at=c(-6,unq,6))
points(unq,rep(0,nunq),cex=2,pch=16)
```


Meta-information
============
extype: num
exsolution: 2
exname: fundamental_theorem
extol: 0
exextra[numwidth,logical]: TRUE
