```{r data generation, echo = FALSE, results = "hide"}
## https://cerebralmastication.com/2020/07/27/using-python-sympy-in-a-python-code-chunk-in-rmarkdown/
## In console, I ran: reticulate::conda_install("r-reticulate","sympy")## In console, I ran: reticulate::conda_install("r-reticulate","matplotlib")
library(reticulate)

v1 = sample(seq(1,10,0.01),1)
v2 = sample(seq(1,10,0.01),1)
w1 = sample(seq(0.1,3,0.1),1)
w2 = sample(seq(0.1,3,0.1),1)
vt = sample(seq(10,100,0.01),1)
wt = sample(seq(5,30,1),1)

```

$$c_1x+c_2y\le C$$
$$d_1x+d_2y\le D $$

To determine intersection...

$$y = -\frac{c_1}{c_2}x+\frac{C}{c_2} $$


$$y = -\frac{d_1}{d_2}x+\frac{D}{d_2} $$

$$ -\frac{c_1}{c_2}x+\frac{C}{c_2} = -\frac{d_1}{d_2}x+\frac{D}{d_2}  $$
$$x = \frac{\frac{D}{d_2}-\frac{C}{c_2}}{\frac{d_1}{d_2}-\frac{c_1}{c_2}}$$

$$y = \frac{\frac{D}{d_1}-\frac{C}{c_1}}{\frac{d_2}{d_1}-\frac{c_2}{c_1}}$$



```{python,echo=F}
import sympy as sp
x = sp.symbols("x")
y = sp.symbols("y")
ex1 = sp.parse_expr(r.lh1)
ex2 = sp.parse_expr(r.lh2)
# eq1 = sp.Eq(ex1,int(r.b[0][0]))
eq2 = sp.Eq(ex2,int(r.rh2))
eq2 = sp.simplify(eq2)
lex1 = sp.latex(ex1)
lex2 = sp.latex(ex2)
lat2 = str(sp.latex(eq2)).replace('=','&=')
```

Question
========

Solve the system of equations.

$$\begin{align}
`r py$lex1` &= `r rh1` \\
`r py$lat2`
\end{align}$$


Solution
========

There is no solution.

This system represents a parabola and a non-intersecting line.

```{r,echo=F}
xxx = max(abs(x1),abs(x2))+20
x = seq(-xxx,xxx,0.1)
yA = a*(x-ver[1])^2+ver[2]
yB = (y2-y1)/(x2-x1)*(x-x1)+y1
mm = max(abs(y1),abs(y2))+5
plot(x,yA,type="l",ylim=c(-mm,mm),lwd=3,ylab="y")
lines(x,yB,type="l",lwd=2)
abline(h=0)
abline(v=0)
```



Meta-information
============
extype: string
exsolution: nil
exname: nonlinear_system_parabola_line_0_solution
